name: "godot-ci export"
on:
  push:
    tags:
      - '*' 

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: Microwave-Man!
  PROJECT_PATH: .

# Permissions required to create a release
permissions:
  contents: write

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/Microwave-Man-Windows.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-artifact
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" "$EXPORT_DIR/linux/Microwave-Man-Linux.x86_64"
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: linux-artifact
          path: build/linux

  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Zip Web Export
        run: |
          apt-get update && apt-get install -y zip
          cd build/web
          # Zips the contents of the web folder
          zip -r ../Microwave-Man-Web.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: web-artifact
          # Upload the zip file specifically
          path: build/Microwave-Man-Web.zip

  export-mac:
    name: Mac Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/Microwave-Man-MacOS.zip"
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: mac-artifact
          path: build/mac

  export-pck:
    name: PCK Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: PCK Build
        run: |
          mkdir -v -p build/pck
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          # Using --export-pack instead of --export-release to generate standalone .pck file
          godot --headless --verbose --export-pack "Linux/X11" "$EXPORT_DIR/pck/Microwave-Man.pck"
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: pck-artifact
          path: build/pck

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [export-windows, export-linux, export-web, export-mac, export-pck]
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v7
        with:
          path: release_files
          merge-multiple: true # Flattens files into the release_files folder

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release_files/*